# Generated by Django 4.0.3 on 2022-04-05 13:57

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addService',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=20)),
                ('SlugField', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
