# Generated by Django 4.0.3 on 2022-04-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservice',
            old_name='SlugField',
            new_name='slug',
        ),
    ]
