# Generated by Django 4.0.3 on 2022-04-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_slug_post_slugfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='SlugField',
            new_name='slug',
        ),
    ]
