# Generated by Django 3.2.12 on 2022-04-26 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.FileField(max_length=250, null=True, upload_to='profilePic/')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='Message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('todotitle', models.CharField(max_length=20, null=True)),
                ('tododescription', models.TextField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
