# Generated by Django 4.0.3 on 2022-04-05 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_timestamp_contact_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.FileField(max_length=250, null=True, upload_to='./profilePic/')),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
