# Generated by Django 4.0.3 on 2022-04-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profilePic',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profilePic/'),
        ),
    ]
